In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Ejemplo de documentos
documents = [
    "El perro ladra",
    "El gato maúlla",
    "El perro y el gato son amigos",
    "El perro ladra y el gato maúlla"
]

# Crear el modelo BoW
vectorizer = CountVectorizer()

# Ajustar y transformar los documentos en vectores
X = vectorizer.fit_transform(documents)

# Mostrar el vocabulario
print("Vocabulario:", vectorizer.vocabulary_)

# Mostrar la representación BoW de los documentos
print("Representación BoW:\n", X.toarray())

Vocabulario: {'el': 1, 'perro': 5, 'ladra': 3, 'gato': 2, 'maúlla': 4, 'son': 6, 'amigos': 0}
Representación BoW:
 [[0 1 0 1 0 1 0]
 [0 1 1 0 1 0 0]
 [1 2 1 0 0 1 1]
 [0 2 1 1 1 1 0]]


C:\Users\plopezme\AppData\Roaming\Python\Python37\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


In [ ]:
import gensim
from gensim.models import Word2Vec

# Ejemplo de corpus de documentos
sentences = [
    ['el', 'perro', 'ladra'],
    ['el', 'gato', 'maúlla'],
    ['el', 'perro', 'y', 'el', 'gato', 'son', 'amigos'],
    ['el', 'perro', 'ladra', 'y', 'el', 'gato', 'maúlla']
]

# Entrenar el modelo Word2Vec
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

# Obtener el vector de la palabra 'perro'
vector = model.wv['perro']
print( "Vector de 'perro':\n", vector, "de Tamaño ", vector.shape[0])


# Encontrar palabras similares a 'perro'
similar_words = model.wv.most_similar('perro')
print("Palabras similares a 'perro':\n", similar_words)


Vector de 'perro':
 [ 9.4563962e-05  3.0773187e-03 -6.8126465e-03 -1.3754654e-03
  7.6685809e-03  7.3464084e-03 -3.6732983e-03  2.6427007e-03
 -8.3171297e-03  6.2054847e-03 -4.6373224e-03 -3.1641079e-03
  9.3113566e-03  8.7338447e-04  7.4907015e-03 -6.0740639e-03
  5.1605059e-03  9.9228211e-03 -8.4573915e-03 -5.1356913e-03
 -7.0648384e-03 -4.8626517e-03 -3.7785650e-03 -8.5362010e-03
  7.9556061e-03 -4.8439382e-03  8.4236125e-03  5.2625705e-03
 -6.5500261e-03  3.9578700e-03  5.4701497e-03 -7.4265362e-03
 -7.4057197e-03 -2.4752307e-03 -8.6257271e-03 -1.5815735e-03
 -4.0343284e-04  3.2996845e-03  1.4418793e-03 -8.8142155e-04
 -5.5940580e-03  1.7303658e-03 -8.9737179e-04  6.7936899e-03
  3.9735888e-03  4.5294715e-03  1.4343048e-03 -2.6998566e-03
 -4.3668128e-03 -1.0320758e-03  1.4370275e-03 -2.6460099e-03
 -7.0737838e-03 -7.8053069e-03 -9.1217877e-03 -5.9351707e-03
 -1.8474245e-03 -4.3238713e-03 -6.4606713e-03 -3.7173224e-03
  4.2891572e-03 -3.7390448e-03  8.3781742e-03  1.5339922e-03
 -7.

In [ ]:
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument

# Ejemplo de corpus de documentos
documents = [
    TaggedDocument(words=['el', 'perro', 'ladra'], tags=['doc1']),
    TaggedDocument(words=['el', 'gato', 'maúlla'], tags=['doc2']),
    TaggedDocument(words=['el', 'perro', 'y', 'el', 'gato', 'son', 'amigos'], tags=['doc3']),
    TaggedDocument(words=['el', 'perro', 'ladra', 'y', 'el', 'gato', 'maúlla'], tags=['doc4'])
]

# Entrenar el modelo Doc2Vec
model = Doc2Vec(documents, vector_size=100, window=5, min_count=1, workers=4)

# Obtener el vector del documento 'doc1'
vector = model.dv['doc1']
print("Vector de 'doc1':\n", vector, "de Tamaño ", vector.shape[0])

# Encontrar documentos similares a 'doc1'
similar_docs = model.dv.most_similar('doc1')
print("Documentos similares a 'doc1':\n", similar_docs)


Vector de 'doc1':
 [-0.00523712 -0.00598646 -0.00987788  0.00855222  0.00357316  0.00026141
 -0.00987699 -0.00517174 -0.00971827  0.00201409  0.00282551  0.00464802
 -0.00430254 -0.00314885 -0.00307666 -0.00871805  0.00217124  0.00922597
 -0.00950408 -0.00345932 -0.00377704  0.00260302 -0.00568931  0.00262589
  0.00580102 -0.0081068  -0.00833266 -0.00995493  0.00493033 -0.00912276
  0.0058403   0.00679778 -0.00650261 -0.00452599 -0.00125707  0.00164952
 -0.00148704 -0.00854769 -0.00360297  0.00172834 -0.00205181 -0.00722613
  0.00419036 -0.00857468  0.00270903 -0.00461519  0.00064432 -0.00205395
  0.00541016 -0.00801009 -0.00212653 -0.00010093 -0.00664452 -0.00652926
 -0.00193493  0.00880966 -0.00126062  0.00354016 -0.00575008  0.00881831
  0.0029191   0.00928757  0.00435432 -0.00419932  0.00224115 -0.00441026
  0.00578298  0.00183784 -0.0022752  -0.00587963 -0.00803539 -0.00085109
 -0.00894284 -0.00922349 -0.00793785  0.00216816 -0.00650811 -0.00779177
  0.00212847  0.00205082  0.0083